export type Ingredient = {
  id: string;
  name: string;
  category: 'Proteins' | 'Produce' | 'Dairy' | 'Pantry' | 'Nuts' | 'Grains';
  isAllergen: boolean;
  allergenType?: string;
};

export const INGREDIENTS_REGISTRY: Ingredient[] = [
  // Proteins
  { id: "1", name: "Wagyu Beef", category: "Proteins", isAllergen: false },
  { id: "2", name: "Atlantic Salmon", category: "Proteins", isAllergen: true, allergenType: "Fish" },
  { id: "3", name: "Chicken Breast", category: "Proteins", isAllergen: false },
  { id: "4", name: "Duck Breast", category: "Proteins", isAllergen: false },
  { id: "5", name: "Pork Belly", category: "Proteins", isAllergen: false },
  { id: "6", name: "Lamb Rack", category: "Proteins", isAllergen: false },
  { id: "7", name: "Veal Tenderloin", category: "Proteins", isAllergen: false },
  { id: "8", name: "Shrimp", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "9", name: "Scallops", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "10", name: "Lobster", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "11", name: "Crab Meat", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "12", name: "Cod Fillet", category: "Proteins", isAllergen: true, allergenType: "Fish" },
  { id: "13", name: "Tuna", category: "Proteins", isAllergen: true, allergenType: "Fish" },
  { id: "14", name: "Mussels", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "15", name: "Clams", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "16", name: "Eggs", category: "Proteins", isAllergen: true, allergenType: "Egg" },
  { id: "17", name: "Tofu", category: "Proteins", isAllergen: true, allergenType: "Soy" },
  { id: "18", name: "Tempeh", category: "Proteins", isAllergen: true, allergenType: "Soy" },
  { id: "19", name: "Turkey Breast", category: "Proteins", isAllergen: false },
  { id: "20", name: "Venison", category: "Proteins", isAllergen: false },

  // Dairy
  { id: "21", name: "Heavy Cream", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "22", name: "Whole Milk", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "23", name: "Butter", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "24", name: "Parmesan Cheese", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "25", name: "Goat Cheese", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "26", name: "Mozzarella", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "27", name: "Cheddar Cheese", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "28", name: "Gruyere", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "29", name: "Ricotta", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "30", name: "Mascarpone", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "31", name: "Yogurt", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "32", name: "Sour Cream", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "33", name: "Buttermilk", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "34", name: "Blue Cheese", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "35", name: "Feta Cheese", category: "Dairy", isAllergen: true, allergenType: "Lactose" },

  // Produce
  { id: "36", name: "Yellow Onion", category: "Produce", isAllergen: false },
  { id: "37", name: "Garlic", category: "Produce", isAllergen: false },
  { id: "38", name: "Shallots", category: "Produce", isAllergen: false },
  { id: "39", name: "Tomatoes", category: "Produce", isAllergen: false },
  { id: "40", name: "Cherry Tomatoes", category: "Produce", isAllergen: false },
  { id: "41", name: "Carrots", category: "Produce", isAllergen: false },
  { id: "42", name: "Celery", category: "Produce", isAllergen: true, allergenType: "Celery" },
  { id: "43", name: "Potatoes", category: "Produce", isAllergen: false },
  { id: "44", name: "Sweet Potatoes", category: "Produce", isAllergen: false },
  { id: "45", name: "Spinach", category: "Produce", isAllergen: false },
  { id: "46", name: "Kale", category: "Produce", isAllergen: false },
  { id: "47", name: "Arugula", category: "Produce", isAllergen: false },
  { id: "48", name: "Mushrooms", category: "Produce", isAllergen: false },
  { id: "49", name: "Portobello Mushrooms", category: "Produce", isAllergen: false },
  { id: "50", name: "Bell Peppers", category: "Produce", isAllergen: false },
  { id: "51", name: "Zucchini", category: "Produce", isAllergen: false },
  { id: "52", name: "Eggplant", category: "Produce", isAllergen: false },
  { id: "53", name: "Broccoli", category: "Produce", isAllergen: false },
  { id: "54", name: "Cauliflower", category: "Produce", isAllergen: false },
  { id: "55", name: "Asparagus", category: "Produce", isAllergen: false },
  { id: "56", name: "Lemons", category: "Produce", isAllergen: false },
  { id: "57", name: "Limes", category: "Produce", isAllergen: false },
  { id: "58", name: "Avocado", category: "Produce", isAllergen: false },
  { id: "59", name: "Fresh Basil", category: "Produce", isAllergen: false },
  { id: "60", name: "Cilantro", category: "Produce", isAllergen: false },
  { id: "61", name: "Parsley", category: "Produce", isAllergen: false },
  { id: "62", name: "Rosemary", category: "Produce", isAllergen: false },
  { id: "63", name: "Thyme", category: "Produce", isAllergen: false },
  { id: "64", name: "Ginger", category: "Produce", isAllergen: false },
  { id: "65", name: "Green Onions", category: "Produce", isAllergen: false },

  // Pantry
  { id: "66", name: "Truffle Oil", category: "Pantry", isAllergen: false },
  { id: "67", name: "Olive Oil", category: "Pantry", isAllergen: false },
  { id: "68", name: "Sesame Oil", category: "Pantry", isAllergen: true, allergenType: "Sesame" },
  { id: "69", name: "Soy Sauce", category: "Pantry", isAllergen: true, allergenType: "Soy" },
  { id: "70", name: "Tamari", category: "Pantry", isAllergen: true, allergenType: "Soy" },
  { id: "71", name: "Fish Sauce", category: "Pantry", isAllergen: true, allergenType: "Fish" },
  { id: "72", name: "Balsamic Vinegar", category: "Pantry", isAllergen: false },
  { id: "73", name: "Red Wine Vinegar", category: "Pantry", isAllergen: false },
  { id: "74", name: "Dijon Mustard", category: "Pantry", isAllergen: true, allergenType: "Mustard" },
  { id: "75", name: "Mayonnaise", category: "Pantry", isAllergen: true, allergenType: "Egg" },
  { id: "76", name: "Tomato Paste", category: "Pantry", isAllergen: false },
  { id: "77", name: "Chicken Stock", category: "Pantry", isAllergen: false },
  { id: "78", name: "Beef Stock", category: "Pantry", isAllergen: false },
  { id: "79", name: "Coconut Milk", category: "Pantry", isAllergen: false },
  { id: "80", name: "Honey", category: "Pantry", isAllergen: false },
  { id: "81", name: "Maple Syrup", category: "Pantry", isAllergen: false },
  { id: "82", name: "Sea Salt", category: "Pantry", isAllergen: false },
  { id: "83", name: "Black Pepper", category: "Pantry", isAllergen: false },
  { id: "84", name: "Smoked Paprika", category: "Pantry", isAllergen: false },
  { id: "85", name: "Cumin", category: "Pantry", isAllergen: false },
  { id: "86", name: "Curry Powder", category: "Pantry", isAllergen: false },
  { id: "87", name: "Cornstarch", category: "Pantry", isAllergen: false },
  { id: "88", name: "Panko Breadcrumbs", category: "Pantry", isAllergen: true, allergenType: "Gluten" },
  { id: "89", name: "Flour", category: "Pantry", isAllergen: true, allergenType: "Gluten" },
  { id: "90", name: "Sugar", category: "Pantry", isAllergen: false },

  // Nuts
  { id: "91", name: "Peanuts", category: "Nuts", isAllergen: true, allergenType: "Peanut" },
  { id: "92", name: "Almonds", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },
  { id: "93", name: "Walnuts", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },
  { id: "94", name: "Cashews", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },
  { id: "95", name: "Pistachios", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },

  // Grains
  { id: "96", name: "Sourdough Starter", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "97", name: "Arborio Rice", category: "Grains", isAllergen: false },
  { id: "98", name: "Jasmine Rice", category: "Grains", isAllergen: false },
  { id: "99", name: "Quinoa", category: "Grains", isAllergen: false },
  { id: "100", name: "Farro", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "101", name: "Spaghetti", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "102", name: "Udon Noodles", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "103", name: "Couscous", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "104", name: "Rolled Oats", category: "Grains", isAllergen: false },
  { id: "105", name: "Breadcrumbs", category: "Grains", isAllergen: true, allergenType: "Gluten" },

  // Additional Proteins
  { id: "106", name: "Short Ribs", category: "Proteins", isAllergen: false },
  { id: "107", name: "Ground Beef", category: "Proteins", isAllergen: false },
  { id: "108", name: "Prosciutto", category: "Proteins", isAllergen: false },
  { id: "109", name: "Bacon", category: "Proteins", isAllergen: false },
  { id: "110", name: "Chorizo", category: "Proteins", isAllergen: false },
  { id: "111", name: "Italian Sausage", category: "Proteins", isAllergen: false },
  { id: "112", name: "Octopus", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "113", name: "Squid", category: "Proteins", isAllergen: true, allergenType: "Shellfish" },
  { id: "114", name: "Anchovies", category: "Proteins", isAllergen: true, allergenType: "Fish" },
  { id: "115", name: "Sardines", category: "Proteins", isAllergen: true, allergenType: "Fish" },
  { id: "116", name: "Halibut", category: "Proteins", isAllergen: true, allergenType: "Fish" },
  { id: "117", name: "Mackerel", category: "Proteins", isAllergen: true, allergenType: "Fish" },
  { id: "118", name: "Duck Confit", category: "Proteins", isAllergen: false },
  { id: "119", name: "Foie Gras", category: "Proteins", isAllergen: false },
  { id: "120", name: "Chicken Thighs", category: "Proteins", isAllergen: false },

  // Additional Dairy
  { id: "121", name: "Brie", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "122", name: "Camembert", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "123", name: "Cream Cheese", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "124", name: "Burrata", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "125", name: "Halloumi", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "126", name: "Ghee", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "127", name: "Evaporated Milk", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "128", name: "Condensed Milk", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "129", name: "Whipping Cream", category: "Dairy", isAllergen: true, allergenType: "Lactose" },
  { id: "130", name: "Pecorino Romano", category: "Dairy", isAllergen: true, allergenType: "Lactose" },

  // Additional Produce
  { id: "131", name: "Leeks", category: "Produce", isAllergen: false },
  { id: "132", name: "Fennel", category: "Produce", isAllergen: false },
  { id: "133", name: "Radishes", category: "Produce", isAllergen: false },
  { id: "134", name: "Beets", category: "Produce", isAllergen: false },
  { id: "135", name: "Butternut Squash", category: "Produce", isAllergen: false },
  { id: "136", name: "Cucumber", category: "Produce", isAllergen: false },
  { id: "137", name: "Snap Peas", category: "Produce", isAllergen: false },
  { id: "138", name: "Brussels Sprouts", category: "Produce", isAllergen: false },
  { id: "139", name: "Red Cabbage", category: "Produce", isAllergen: false },
  { id: "140", name: "Bok Choy", category: "Produce", isAllergen: false },
  { id: "141", name: "Jalapeños", category: "Produce", isAllergen: false },
  { id: "142", name: "Thai Chili", category: "Produce", isAllergen: false },
  { id: "143", name: "Serrano Peppers", category: "Produce", isAllergen: false },
  { id: "144", name: "Mint", category: "Produce", isAllergen: false },
  { id: "145", name: "Dill", category: "Produce", isAllergen: false },
  { id: "146", name: "Oregano", category: "Produce", isAllergen: false },
  { id: "147", name: "Sage", category: "Produce", isAllergen: false },
  { id: "148", name: "Chives", category: "Produce", isAllergen: false },
  { id: "149", name: "Apples", category: "Produce", isAllergen: false },
  { id: "150", name: "Pears", category: "Produce", isAllergen: false },

  // Additional Pantry
  { id: "151", name: "Rice Vinegar", category: "Pantry", isAllergen: false },
  { id: "152", name: "Apple Cider Vinegar", category: "Pantry", isAllergen: false },
  { id: "153", name: "Worcestershire Sauce", category: "Pantry", isAllergen: true, allergenType: "Fish" },
  { id: "154", name: "Sriracha", category: "Pantry", isAllergen: false },
  { id: "155", name: "Harissa Paste", category: "Pantry", isAllergen: false },
  { id: "156", name: "Miso Paste", category: "Pantry", isAllergen: true, allergenType: "Soy" },
  { id: "157", name: "Tahini", category: "Pantry", isAllergen: true, allergenType: "Sesame" },
  { id: "158", name: "Pesto", category: "Pantry", isAllergen: true, allergenType: "Tree Nut" },
  { id: "159", name: "Sun-Dried Tomatoes", category: "Pantry", isAllergen: false },
  { id: "160", name: "Capers", category: "Pantry", isAllergen: false },
  { id: "161", name: "Olives", category: "Pantry", isAllergen: false },
  { id: "162", name: "Chickpeas", category: "Pantry", isAllergen: false },
  { id: "163", name: "Black Beans", category: "Pantry", isAllergen: false },
  { id: "164", name: "Cannellini Beans", category: "Pantry", isAllergen: false },
  { id: "165", name: "Lentils", category: "Pantry", isAllergen: false },
  { id: "166", name: "Pineapple Juice", category: "Pantry", isAllergen: false },
  { id: "167", name: "Vanilla Extract", category: "Pantry", isAllergen: false },
  { id: "168", name: "Cinnamon", category: "Pantry", isAllergen: false },
  { id: "169", name: "Nutmeg", category: "Pantry", isAllergen: false },
  { id: "170", name: "Bay Leaves", category: "Pantry", isAllergen: false },

  // Additional Nuts
  { id: "171", name: "Hazelnuts", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },
  { id: "172", name: "Macadamia Nuts", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },
  { id: "173", name: "Pine Nuts", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },
  { id: "174", name: "Brazil Nuts", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },
  { id: "175", name: "Chestnuts", category: "Nuts", isAllergen: true, allergenType: "Tree Nut" },

  // Additional Grains
  { id: "176", name: "Basmati Rice", category: "Grains", isAllergen: false },
  { id: "177", name: "Wild Rice", category: "Grains", isAllergen: false },
  { id: "178", name: "Brown Rice", category: "Grains", isAllergen: false },
  { id: "179", name: "Polenta", category: "Grains", isAllergen: false },
  { id: "180", name: "Cornmeal", category: "Grains", isAllergen: false },
  { id: "181", name: "Ramen Noodles", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "182", name: "Rice Noodles", category: "Grains", isAllergen: false },
  { id: "183", name: "Soba Noodles", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "184", name: "Pita Bread", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "185", name: "Ciabatta Bread", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "186", name: "Pizza Dough", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "187", name: "Tortillas", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "188", name: "Barley", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "189", name: "Bulgur", category: "Grains", isAllergen: true, allergenType: "Gluten" },
  { id: "190", name: "Cereal Oats", category: "Grains", isAllergen: false }
];