"use client"

import { useEffect, useState } from "react"
import { usePathname } from "next/navigation"
import { useInboxRealtime } from "./use-inbox-realtime"

interface Conversation {
  id: string
  created_at: string
  conversation_type?: string
  participants?: any[]
  unreadCount?: number
  latestMessage?: {
    id: string
    content: string
    created_at: string
    sender_id: string
    message_type: string
  }
}

interface Props {
  initialConversations: Conversation[]
  currentUserId: string
}

export function useInbox({
  initialConversations,
  currentUserId,
}: Props) {
  const [conversations, setConversations] =
    useState<Conversation[]>(initialConversations)
  const pathname = usePathname()

  // Automatically clear unread badge state when a thread path matches active window viewport
  useEffect(() => {
    const match = pathname?.match(/\/messages\/([a-zA-Z0-9-]+)/)
    if (match) {
      const activeId = match[1]
      setConversations(prev => prev.map(c => 
        c.id === activeId ? { ...c, unreadCount: 0 } : c
      ))
    }
  }, [pathname])

  useInboxRealtime({
    onConversationUpdate: (updatedConversation: Conversation) => {
      setConversations((prev) => {
        const currentChat = prev.find((c) => c.id === updatedConversation.id)
        const exists = !!currentChat

        // Read current routing state to check alignment
        const match = pathname?.match(/\/messages\/([a-zA-Z0-9-]+)/)
        const activeChatId = match ? match[1] : null
        const isCurrentActiveChat = activeChatId === updatedConversation.id
        const isMe = updatedConversation.latestMessage?.sender_id === currentUserId

        let newUnreadCount = updatedConversation.unreadCount ?? currentChat?.unreadCount ?? 0

        // Increment badging count if message is incoming, unread, and not generated by current terminal session
        if (
          updatedConversation.latestMessage &&
          updatedConversation.latestMessage.id !== currentChat?.latestMessage?.id &&
          !isMe &&
          !isCurrentActiveChat
        ) {
          newUnreadCount = (currentChat?.unreadCount ?? 0) + 1
        } else if (isCurrentActiveChat) {
          newUnreadCount = 0
        }

        const conversationWithUnread = {
          ...updatedConversation,
          unreadCount: newUnreadCount
        }

        /**
         * NEW CONVERSATION
         */
        if (!exists) {
          return [
            conversationWithUnread,
            ...prev,
          ]
        }

        /**
         * UPDATE EXISTING & BUBBLE TO TOP
         */
        return prev
          .map((conversation) =>
            conversation.id === updatedConversation.id
              ? conversationWithUnread
              : conversation
          )
          .sort((a, b) => {
            const aTime =
              a.latestMessage?.created_at ??
              a.created_at

            const bTime =
              b.latestMessage?.created_at ??
              b.created_at

            return (
              new Date(bTime).getTime() -
              new Date(aTime).getTime()
            )
          })
      })
    },
  })

  useEffect(() => {
    setConversations(initialConversations)
  }, [initialConversations])

  return {
    conversations,
  }
}